### ISSUE TITLE
Error after upgrading from 19.9.0 to 19.12.0;  'HttpProtocol' object has no attribute '_body_chunks

### ISSUE THREAD

**Issue by sevaho** [huge-success/sanic#1746]
After upgrading to the newest Sanic, it breaks with the following logs:

```
Unhandled exception in event loop
Traceback (most recent call last):
  File "uvloop/handles/streamserver.pyx", line 143, in uvloop.loop.__uv_streamserver_on_listen
  File "uvloop/handles/streamserver.pyx", line 67, in uvloop.loop.UVStreamServer._on_listen
  File "/usr/local/lib/python3.8/site-packages/sanic/server.py", line 152, in __init__
    self._body_chunks = deque()
AttributeError: 'HttpProtocol' object has no attribute '_body_chunks'
```

**Comment by Tronic** [comment]
Fixed in #1743 and should be merged to master soon.

**Comment by ahopkins** [comment]
Awaiting merge from @huge-success/sanic-release-managers. Closing this now. Thanks for the callout.
